# This is a config for E2B sandbox template.
# You can use template ID (yjjh01164k4rktmuspxk) or template name (nova-next-js-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("nova-next-js-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("nova-next-js-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nova-next-js-test-2')

team_id = "a1bbf52d-63c5-43c9-bade-a62b6f420657"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "nova-next-js-test-2"
template_id = "yjjh01164k4rktmuspxk"
